language: python
python: 3.7.2
dist: xenial
sudo: true
install:
  - pip install -e .
jobs:
  include:
    - stage: Run Tests
      script: pytest
    - stage: Run coverage
      script: pytest --cov=pathing tests/
    - stage: Run linter
      script: pylint pathing
