language: python
python: 3.7.2
dist: xenial
sudo: true
jobs:
  include:
    - stage: Setup and Run Tests
      script: python3 -m venv .env
      script: source .env/bin/activate
      script: pip install -r requirements.txt
      script: pip install -e .
      script: pytest
