language: python
python: 3.7.2
dist: xenial
sudo: true
jobs:
  include:
    stage: Setup Virtual Environment
    script:
      python3 -m venv .env
  include:
    stage: Enter Virtual Environment
    script:
      source .env/bin/activate
  include:
    stage: Install requirements
    script:
      pip install -r requirements.txt
  include:
    stage: Make editable install of current directory
    script:
      pip install -e .
  include:
    stage: Run tests
    script:
      pytest
