language: python
python: 3.7.2
dist: xenial
sudo: true
install:
  -python3 -m venv .env
  -source .env/bin/activate
  -pip install -r requirements.txt
  pip install -e .
jobs:
  include:
    - stage: Run Tests
      script: pytest
